name: Linter

on: [push]

jobs:
  cpp:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-python@v2

    - name: Install cpplint
      shell: bash
      run: pip install cpplint

    - name: Run cpplint
      shell: bash
      run: cpplint --recursive --filter="-whitespace/braces,-whitespace/indent,-whitespace/comments,-runtime/indentation_namespace,-build/c++11,-whitespace/empty_loop_body" include src
